# bash into container $>
# docker exec -it 5831c1269132 bash

# create new project
# $> docker run --name polymer-project --rm -p 8081:8081 -v $(pwd):/home/app/test gvand/polymer polymer init polymer-2-starter-kit

# serve project
# $> docker run --name polymer-project --rm -p 8081:8081 -v $(pwd):/home/app/test gvand/polymer polymer serve -H 0.0.0.0

version: "2.1"

services:

  proxy:
    container_name: proxy
    image: traefik
    restart: always
    networks:
      - app-network
    ports:
      - "80:80"
      - "8080:8080"
      - "3000:3000"
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

  polymer:
    container_name: polymer
    image: ing/polymer
    build:
      context: ./polymer
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8081"
      - "traefik.protocol=http"
      - "traefik.backend=polymer"
      - "traefik.frontend.rule=Host:docker.localhost"
      - "traefik.polymer.port=8081"
      - "traefik.polymer.frontend.entryPoints=http"
      - "traefik.sync3000.port=3000"
      - "traefik.sync3000.frontend.entryPoints=http3000"
      - "traefik.sync3001.port=3001"
      - "traefik.sync3001.frontend.entryPoints=http3001"
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
    ports:
      - "8081"
      - "3000"
      - "3001"
    volumes:
      - ./polymer:/home/app/test
      - ./polymer/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

  bower:
    container_name: bower
    image: ing/bower
    build:
      context: ./bower
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8082"
      - "traefik.backend=bower"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:docker.localhost;PathPrefix:/bower_components/"
      - "traefik.docker.network=app-network"
      - "traefik.enable=true"
    ports:
      - "8082"
    volumes:
      - ./bower:/home/app/test
      - ./bower/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

  api:
    container_name: api
    image: ing/api
    build:
      context: ./api
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8083"
      - "traefik.backend=api"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:api.docker.localhost"
      - "traefik.docker.network=app-network"
      - "traefik.enable=true"
    ports:
      - "8083"
    volumes:
      - ./api:/home/app/test
      - ./api/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

networks:
    app-network:
      driver: bridge