# bash into a running container
# $> docker exec -it 5831c1269132 bash

# create new polymer project
# $> docker run --name polymer-project --rm -p 8081:8081 -v $(pwd):/home/app/test gvand/polymer polymer init polymer-2-starter-kit

version: "2.1"

services:

  proxy:
    container_name: proxy
    image: traefik
    restart: always
    networks:
      - app-network
    labels:
      - "traefik.backend=proxy"
      - "traefik.admin.frontend.rule=Host:admin.docker.localhost"
      - "traefik.admin.port=9001"
    ports:
      - "80:80"
      - "8080:8080"
      - "9001:9001"
#      - "3000:3000"
#      - "3001:3001"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  polymer:
    container_name: polymer
    image: ing/polymer
    build:
      context: ./polymer
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8081"
      - "traefik.protocol=http"
      - "traefik.backend=polymer"
      - "traefik.frontend.rule=Host:docker.localhost"
      - "traefik.frontend.entryPoints=http"
      - "traefik.enable=true"
    ports:
      - "8081"
#      - "8081:8081"
    volumes:
      - ./polymer:/home/app/test
      - ./polymer/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

  bower:
    container_name: bower
    image: ing/bower
    build:
      context: ./bower
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8082"
      - "traefik.protocol=http"
      - "traefik.backend=bower"
      - "traefik.frontend.rule=Host:docker.localhost;PathPrefix:/bower_components/"
      - "traefik.enable=true"
    ports:
      - "8082"
    volumes:
      - ./bower:/home/app/test
      - ./bower/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

  api:
    container_name: api
    image: ing/api
    build:
      context: ./api
      dockerfile: Dockerfile
    labels:
      - "traefik.port=8083"
      - "traefik.backend=api"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:api.docker.localhost"
      - "traefik.enable=true"
      - "traefik.priority=10"
    ports:
      - "8083"
    volumes:
      - ./api:/home/app/test
      - ./api/node_modules:/home/app/test/node_modules
    working_dir: /home/app/test
    command: ["npm", "start"]
    networks:
      - app-network

#  browsersync:
#    container_name: browsersync
#    image: ustwo/browser-sync
#    command: start --proxy 'polymer:8081' --files './*.html', 'src/*.html' --reload-debounce 2000 --notify false
#    labels:
#      - "traefik.backend=browsersync"
#      - "traefik.proxy.frontend.rule=Host:bs.docker.localhost"
#      - "traefik.proxy.frontend.entryPoints=http,http-3000"
#      - "traefik.proxy.port=3000"
#      - "traefik.admin.frontend.rule=Host:bs.docker.localhost"
#      - "traefik.admin.frontend.entryPoints=http,http-3001"
#      - "traefik.admin.port=3001"
#      - "traefik.enable=true"
#    ports:
#      - "3000:3000"
#      - "3001:3001"
#      - "80"
#      - "8080"
#      - "3000"
#      - "3001"

    networks:
      - app-network

networks:
    app-network:
      driver: bridge