debug = true
checkNewVersion = true
logLevel = "DEBUG"
defaultEntryPoints = ["http","http3000","http3001"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http3000]
  address = ":3000"
  [entryPoints.http3001]
  address = ":3001"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false